from snakemake.utils import min_version, validate


# Load config file
configfile: "config/config.yml"


validate(config, "schemas/config.schema.yaml")


include: "scripts/general_functions.smk"


# Set minimum snakemake version
min_version("8.25.5")


# Define Docker container
containerized: f"docker://niekwit/gps-orfeome:{DOCKER_VERSION}"


# Load stuff
csv, fasta = csv()
orfeome_name = config["orfeome_name"]
EXT = get_extension()
SAMPLES = sample_names()
COMPARISONS, HIT_TH, SD_TH, PROP_TH, PEN_TH = wildcard_values()


# Import rules
include: "rules/qc.smk"
include: "rules/count.smk"
include: "rules/stats.smk"


# Set target rule
rule all:
    input:
        targets(),


# Save snakemake terminal output to log file
time = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
snake_log = f"logs/snakemake/{time}_snakemake.log"
os.makedirs("logs/snakemake", exist_ok=True)


onsuccess:
    shell("cp -v {log} {snake_log}")
    logger.info("Analysis finished successfully!")


onerror:
    shell("cp -v {log} {snake_log}")
    logger.info(f"Analysis failed...\nCheck {snake_log} for details")
