include: "scripts/general_functions.smk"

# Workflow version
VERSION = "v0.5.0" 

# Set minimum snakemake version
min_version("8.25.5")

# Wrapper version
wrapper_version = "v5.2.1"

logger.info(f"Workflow version: {VERSION}")
logger.info(f"Wrapper version: {wrapper_version}")

# Define report file
#report: "report/workflow.rst"

# Define Docker container
containerized: f"docker://niekwit/gps-orfeome:{VERSION}"

# Load config file
configfile: "config/config.yml"
#validate(config, "schemas/config.schema.yaml")

# Load stuff
csv,fasta = csv()
orfeome_name = config["orfeome_name"]
SAMPLES = sample_names()
COMPARISONS = comparisons()
THRESHOLD = [config["psi"]["hit_threshold"]]

# Import rules
include: "rules/qc.smk"
include: "rules/count.smk"
include: "rules/stats.smk"

# Set target rule
rule all:
    input:
        targets()

# Save snakemake terminal output to log file
time = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
snake_log = f"logs/snakemake/{time}_snakemake.log"
os.makedirs("logs/snakemake", exist_ok=True)

onsuccess: 
    shell("cp -v {log} {snake_log}")
    logger.info("Analysis finished successfully!")
onerror:
    shell("cp -v {log} {snake_log}")
    logger.info(f"Analysis failed...\nCheck {snake_log} for details")