orfeome_name: uORFbarcodes

# Number of bins set during sorting of cells 
# (should be the same for each sample)
# With bin_number higher than 1, it is assumed that the user wants to perform
# a protein stability analysis using PSI (Protein Stability Index) as a metric.
# With bin_number = 1, the user wants to perform a pairwise comparison 
# of orf count between two conditions using MAGeCK.
bin_number: 1

cutadapt:
  # Sequence of an adapter ligated to the 5' end. 
  # The adapter and any preceding bases are trimmed.
  five_prime_adapter: AGATCGGAAGAGCAC
  
  # Sequence of an adapter ligated to the 3' end.
  # The adapter and subsequent bases are trimmed.
  three_prime_adapter: AGATCGGAAGAGCGTCGTG
  
  # Extra cutadapt arguments
  extra: "--discard-untrimmed" 

csv: 
  # If no fasta is available, provide a csv file with barcode sequences/names
  name_column: 3 # Column number with barcode names
  sequence_column: 2 # Column number with barcode sequences

# Mismatches allowed during alignment
mismatch: 0 

# MAGeCK is used when bin_number is set to 1
mageck:
  extra_mageck_arguments: "" 
  mageck_control_barcodes: all # All or file with control genes
  fdr: 0.25 # FDR threshold for downstream mageck analysis

# Settings for the protein stability analysis when bin number is higher than 1
bins:
  # Minimum value of sum of barcode counts across all bins to keep
  sob_threshold: 100

  # deltaPSI thresholds for hits and controls
  stringent_hit_threshold: 1
  hit_threshold: 0.5
  control_threshold: 0.25
  
  stringent_negative_hit_threshold: -1
  negative_hit_threshold: -0.5
  negative_control_threshold: -0.25