$schema: "http://json-schema.org/draft-06/schema#"

description: Snakemake configuration file

type: object

properties:
  bin_number:
    description: Number of bins used for FACS
    type: integer
    minimum: 1

  cutadapt:
    description: Cutadapt settings
    type: object
    properties:
      five_prime_adapter:
        description: Sequence of an adapter ligated to the 5' end
        type: string
        pattern: "^[ACGTNacgtn]+$"
        default: ""
      three_prime_adapter:
        description: Sequence of an adapter ligated to the 3' end
        type: string
        pattern: "^[ACGTNacgtn]+$"
        default: ""
      barcode_length:
        description: Length of barcode sequence
        type: integer
        minimum: 0
      extra:
        description: Extra cutadapt arguments
        type: string
        default: ""
    required:
      - five_prime_adapter
      - three_prime_adapter

  csv:
    description: CSV settings
    type: object
    properties:
      gene_column:
        description: Column number with gene names
        type: integer
        minimum: 0
      orf_column:
        description: Column number with unique ORF names
        type: integer
        minimum: 0
      barcode_id_column:
        description: Column with unique barcode IDs
        type: integer
        minimum: 0
      sequence_column:
        description: Column number with barcode sequences
        type: integer
        minimum: 0
    required:
      - gene_column
      - orf_column
      - barcode_id_column
      - sequence_column

  mismatch:
    description: Mismatches allowed during alignment
    type: integer
    minimum: 0
    default: 0

  mageck:
    description: MAGeCK settings
    type: object
    properties:
      run:
        description: Run MAGeCK analysis
        type: boolean
        default: true
      extra_mageck_arguments:
        description: Extra MAGeCK arguments
        type: string
        default: ""
      mageck_control_barcodes:
        description: All or file with control barcodes
        type: string
        default: "all"
      fdr:
        description: FDR threshold for downstream mageck analysis
        type: number
        minimum: 0
        maximum: 1
        default: 0.25
    required:
      - run
      - extra_mageck_arguments
      - mageck_control_barcodes
      - fdr
  
  drugz:
    description: DrugZ settings
    type: object
    properties:
      run:
        description: Run DrugZ analysis
        type: boolean
        default: true
      extra:
        description: Extra DrugZ arguments
        type: string
        default: ""
    required:
      - run
      - extra

  psi:
    description: Protein stability analysis settings
    type: object
    properties:
      sob_threshold:
        description: Minimum value of sum of barcode counts across all bins to keep
        type: integer
        minimum: 0
        default: 100
      hit_threshold:
        description: deltaPSI thresholds for hits
        type: array
        items:
          type: number
          minimum: 0
        default: [0.75, 1.0, 1.25]
      exclude_dual_peaks:
        description: Exclude barcode with dual peaks
        type: boolean
      proportion_threshold:
        description: Proportion threshold for second peak of first peak
        type: array
        items:
          type: number
          minimum: 0
      bc_threshold:
        description: Barcode threshold for hits
        type: integer
        minimum: 0
        default: 2
      sd_threshold:
        description: SD threshold for most stringent hits
        type: array
        items:
          type: number
          minimum: 0
    required:
      - sob_threshold
      - hit_threshold
      - exclude_dual_peaks
      - proportion_threshold
      - bc_threshold
      - sd_threshold

required: 
  - bin_number
  - cutadapt
  - csv
  - mismatch
  - mageck
  - drugz
  - psi