# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-pypi

name: Publish Python Package to PyPI

# This action will run anytime a new release is 'published' on GitHub.
on:
  release:
    types: [published]

# This specifies that the job requires read-only permissions for its contents,
# but write-permissions for packages. This is a security best practice.
permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository's code
    - uses: actions/checkout@v4

    # Step 2: Set up a Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Step 3: Install dependencies for building the package
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    # Step 4: Build the package (sdist and wheel)
    - name: Build package
      run: python -m build

    # Step 5: Publish the package to PyPI
    # This uses the official PyPA action and the API token we stored as a secret.
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.9.0
      with:
        api_token: ${{ secrets.PYPI_API_TOKEN }}